#
# Makefile
#
CC = c99
RM = rm -f
LIBDIR = lib
TESTDIR = tests
SUBDIRS = $(LIBDIR) $(TESTDIR)
lib_LIBRARIES = libailsa.a
test_PROGRAMS = check_kv check_ailsa_list check_kv_list

all: $(lib_LIBRARIES) $(test_PROGRAMS)

lib libs: $(lib_LIBRARIES)

tests:	$(test_PROGRAMS)

$(lib_LIBRARIES):
	$(MAKE) -C $(LIBDIR) $@

$(test_PROGRAMS):	$(lib_LIBRARIES)
	$(MAKE) -C $(TESTDIR) $@

.PHONY: clean

clean:
	for dir in $(SUBDIRS); do \
	  $(MAKE) -C $$dir clean; \
	done
