CFLAGS += -std=c99 -W -Wall -Wshadow -Wcast-qual -Wwrite-strings -D_XOPEN_SOURCE=700
CPPFLAGS += -I../include/

lib_LIBRARIES = libailsa.a

lib libs: $(lib_LIBRARIES)

$(lib_LIBRARIES): libailsa.a(data.o) libailsa.a(generic.o) \
		libailsa.a(sql.o) libailsa.a(networking.o) \
		libailsa.a(logging.o)

libailsa.a(data.o): data.o
	$(AR) $(ARFLAGS) $@ $<

libailsa.a(generic.o): generic.o
	$(AR) $(ARFLAGS) $@ $<

libailsa.a(sql.o): sql.o
	$(AR) $(ARFLAGS) $@ $<

libailsa.a(networking.o): networking.o
	$(AR) $(ARFLAGS) $@ $<

libailsa.a(logging.o): logging.o
	$(AR) $(ARFLAGS) $@ $<

.PHONY:	clean

clean:
	$(RM) *.a *.o
