name: libailsa merge

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create ChangeLog
      run: git log --stat --name-only --date=short --abbrev-commit > ChangeLog
    - name: Setup up build
      run: autoreconf -iv
    - name: Start configuration
      run: ./configure
    - name: Run distbuild
      run: make distcheck
    - name: Archive build artifact
      uses: action/upload-artifact@v3
      with:
        name: libailsa-tgz
        path: *.tar.gz
